"""Make consultant fields nullable

Revision ID: a9c28ace1781
Revises: f7aeea49006c
Create Date: 2026-06-03 18:51:18.243809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c28ace1781'
down_revision: Union[str, Sequence[str], None] = 'f7aeea49006c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultants', 'specialization',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultants', 'consultation_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultants', 'consultation_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('consultants', 'specialization',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
